import {
  Crown,
  Search,
  MessageSquare,
  Brain,
  Scissors,
  Database,
  Users,
  DollarSign,
  Scale,
  Server,
  Music,
  Globe,
  Code,
  TrendingUp,
  UserCheck,
} from "lucide-react"

export interface Agent {
  id: string
  name: string
  shortName: string
  role: string
  status: "OPERATIONAL" | "WARNING" | "ERROR" | "INACTIVE" | "PLANNED" | "EN DESARROLLO"
  color: string
  icon: any
  description: string
  capabilities: string[]
  integrations: string[]
}

export const agentsData: Agent[] = [
  {
    id: "00_CEO_LAG",
    name: "CEO Agent - Coordinador Principal",
    shortName: "00_CEO",
    role: "Orquestación y Coordinación General",
    status: "OPERATIONAL",
    color: "#cb2026",
    icon: Crown,
    description:
      "Agente coordinador principal que orquesta todos los agentes del sistema, delega tareas según prioridades y supervisa métricas generales.",
    capabilities: [
      "Procesamiento de task_queue centralizada",
      "Análisis de métricas de rendimiento",
      "Integración con Google Calendar API",
      "Sistema de notificaciones (Twilio/WhatsApp)",
      "Dashboard de control ejecutivo",
      "Sistema de aprendizaje adaptativo",
    ],
    integrations: ["Todos los agentes", "Google Calendar", "Twilio", "WhatsApp"],
  },
  {
    id: "01_SEO_LAG",
    name: "SEO Agent - Optimización SEO",
    shortName: "01_SEO",
    role: "Análisis y Optimización SEO",
    status: "OPERATIONAL",
    color: "#10b981",
    icon: Search,
    description:
      "Especialista en análisis de palabras clave trending, optimización de títulos YouTube y investigación de competencia.",
    capabilities: [
      "Análisis de palabras clave trending",
      "Optimización de títulos y descripciones YouTube",
      "Investigación de competencia",
      "Sugerencias de temas de alto impacto",
      "Análisis de performance SEO",
    ],
    integrations: ["00_CEO_LAG", "02_CM_LAG", "11_WPM_LAG", "13_ADS_LAG"],
  },
  {
    id: "02_CM_LAG",
    name: "Community Manager Agent",
    shortName: "02_CM",
    role: "Gestión de Comunidad",
    status: "OPERATIONAL",
    color: "#3b82f6",
    icon: MessageSquare,
    description:
      "Gestión de comentarios YouTube, engagement en redes sociales y respuestas automatizadas inteligentes.",
    capabilities: [
      "Gestión de comentarios YouTube",
      "Engagement en redes sociales",
      "Respuestas automatizadas inteligentes",
      "Análisis de sentiment de audiencia",
      "Programación de posts en redes sociales",
    ],
    integrations: ["00_CEO_LAG", "01_SEO_LAG", "03_PSICO_LAG", "05_MEDIA_LAG"],
  },
  {
    id: "03_PSICO_LAG",
    name: "Psychology Agent - Engagement",
    shortName: "03_PSICO",
    role: "Psicología y Engagement",
    status: "OPERATIONAL",
    color: "#8b5cf6",
    icon: Brain,
    description: "Análisis psicológico de audiencia, optimización de hooks y thumbnails, predicción de engagement.",
    capabilities: [
      "Análisis psicológico de audiencia",
      "Optimización de hooks y thumbnails",
      "Predicción de engagement basado en psicología",
      "Análisis de retención de videos",
      "Sugerencias de storytelling",
    ],
    integrations: ["00_CEO_LAG", "01_SEO_LAG", "02_CM_LAG", "04_CLIP_LAG"],
  },
  {
    id: "04_CLIP_LAG",
    name: "Video Editing Agent",
    shortName: "04_CLIP",
    role: "Edición de Video",
    status: "OPERATIONAL",
    color: "#f59e0b",
    icon: Scissors,
    description:
      "Automatización de edición básica, generación de clips cortos para YouTube Shorts y detección de momentos highlight.",
    capabilities: [
      "Automatización de edición básica",
      "Generación de clips cortos para YouTube Shorts",
      "Detección de momentos highlight",
      "Aplicación de templates de edición",
      "Optimización de audio y video",
    ],
    integrations: ["00_CEO_LAG", "05_MEDIA_LAG", "03_PSICO_LAG", "10_DJ_LAG"],
  },
  {
    id: "05_MEDIA_LAG",
    name: "Media Management Agent",
    shortName: "05_MEDIA",
    role: "Gestión de Media",
    status: "OPERATIONAL",
    color: "#06b6d4",
    icon: Database,
    description:
      "Organización automática de archivos multimedia, detección de duplicados y gestión de biblioteca centralizada.",
    capabilities: [
      "Organización automática de archivos multimedia",
      "Detección y gestión de duplicados",
      "Ingesta post-filmación automatizada",
      "Mantenimiento de biblioteca de medios centralizada",
      "Gestión de versiones de contenido",
      "Distribución multi-plataforma",
    ],
    integrations: ["00_CEO_LAG", "04_CLIP_LAG", "02_CM_LAG", "09_IT_LAG"],
  },
  {
    id: "06_TALENT_LAG",
    name: "Talent Management Agent",
    shortName: "06_TALENT",
    role: "Gestión de Talento",
    status: "OPERATIONAL",
    color: "#ec4899",
    icon: Users,
    description: "Gestión de colaboraciones, scheduling de grabaciones y coordinación con talentos externos.",
    capabilities: [
      "Gestión de colaboraciones",
      "Scheduling de grabaciones",
      "Coordinación con talentos externos",
      "Análisis de performance de colaboradores",
      "Gestión de contratos y pagos",
    ],
    integrations: ["00_CEO_LAG", "07_CASH_LAG", "08_LAW_LAG", "12_DEV_LAG"],
  },
  {
    id: "07_CASH_LAG",
    name: "Finance Agent - Monetización",
    shortName: "07_CASH",
    role: "Finanzas y Monetización",
    status: "EN DESARROLLO",
    color: "#22c55e",
    icon: DollarSign,
    description: "Gestión de ingresos por monetización, análisis de ROI y optimización de revenue streams.",
    capabilities: [
      "Gestión de ingresos por monetización YouTube",
      "Implementación de programas de afiliados",
      "Análisis de ROI y reportes financieros",
      "Gestión de impuestos y contabilidad",
      "Optimización de revenue streams",
      "Generación de propuestas e invoices",
    ],
    integrations: ["00_CEO_LAG", "08_LAW_LAG", "02_CM_LAG", "06_TALENT_LAG", "12_DEV_LAG"],
  },
  {
    id: "08_LAW_LAG",
    name: "Legal Agent - Asesoría Legal",
    shortName: "08_LAW",
    role: "Asesoría Legal",
    status: "EN DESARROLLO",
    color: "#6366f1",
    icon: Scale,
    description: "Redacción de contratos, gestión de derechos de imagen y prevención de riesgos legales.",
    capabilities: [
      "Redacción y revisión de contratos",
      "Gestión de derechos de imagen y copyrights",
      "Elaboración de términos y condiciones",
      "Prevención de riesgos legales",
      "Blindaje de contenido y marca",
    ],
    integrations: ["00_CEO_LAG", "07_CASH_LAG", "06_TALENT_LAG", "12_DEV_LAG"],
  },
  {
    id: "09_IT_LAG",
    name: "IT Management Agent",
    shortName: "09_IT",
    role: "Gestión Técnica",
    status: "EN DESARROLLO",
    color: "#64748b",
    icon: Server,
    description: "Desarrollo y mantenimiento de sistemas, control de hardware/software y gestión de backups.",
    capabilities: [
      "Desarrollo y mantenimiento de sistemas",
      "Control de hardware y software",
      "Gestión de backups (web, medios)",
      "Monitoreo de rendimiento técnico",
      "Solución de problemas técnicos",
    ],
    integrations: ["00_CEO_LAG", "05_MEDIA_LAG", "11_WPM_LAG", "12_DEV_LAG"],
  },
  {
    id: "10_DJ_LAG",
    name: "Music Management Agent",
    shortName: "10_DJ",
    role: "Gestión Musical",
    status: "EN DESARROLLO",
    color: "#f97316",
    icon: Music,
    description: "Búsqueda de música sin derechos, composición básica y sincronización con video.",
    capabilities: [
      "Búsqueda de música y efectos sin derechos",
      "Composición básica de pistas adaptadas",
      "Sincronización de música con video",
      "Curación de bibliotecas musicales",
      "Sugerencias de estilos según trends",
    ],
    integrations: ["00_CEO_LAG", "04_CLIP_LAG", "03_PSICO_LAG"],
  },
  {
    id: "11_WPM_LAG",
    name: "WordPress Management Agent",
    shortName: "11_WPM",
    role: "Gestión WordPress",
    status: "EN DESARROLLO",
    color: "#0ea5e9",
    icon: Globe,
    description: "Gestión y optimización de la web WordPress de LaGrieta.es, desarrollo de plugins propios.",
    capabilities: [
      "Gestión y optimización web WordPress",
      "Desarrollo de plugins propios con Cursor Pro",
      "Seguridad, actualizaciones y backups",
      "Optimización SEO y aumento de tráfico",
      "Preparación para monetización básica",
    ],
    integrations: ["00_CEO_LAG", "01_SEO_LAG", "03_PSICO_LAG", "09_IT_LAG", "13_ADS_LAG"],
  },
  {
    id: "12_DEV_LAG",
    name: "Development Agent",
    shortName: "12_DEV",
    role: "Desarrollo",
    status: "EN DESARROLLO",
    color: "#84cc16",
    icon: Code,
    description: "Desarrollo de websites en React, aplicaciones React Native y apps para Google Play Store.",
    capabilities: [
      "Desarrollo de websites en React",
      "Creación de aplicaciones React Native",
      "Generación de apps para Google Play Store",
      "Ajustes visuales via formulario inteligente",
      "Coordinación con sistema financiero",
    ],
    integrations: ["00_CEO_LAG", "06_TALENT_LAG", "07_CASH_LAG", "08_LAW_LAG", "11_WPM_LAG"],
  },
  {
    id: "13_ADS_LAG",
    name: "Advertising Agent",
    shortName: "13_ADS",
    role: "Publicidad",
    status: "EN DESARROLLO",
    color: "#ef4444",
    icon: TrendingUp,
    description: "Impulso de contenido masivo, estrategias semanales con IA y preparación para campañas publicitarias.",
    capabilities: [
      "Impulso de contenido masivo",
      "Estrategias semanales con IA",
      "Preparación para campañas publicitarias",
      "Sugerencias basadas en Google Analytics",
      "Coordinación multi-agente",
    ],
    integrations: ["00_CEO_LAG", "11_WPM_LAG", "01_SEO_LAG", "03_PSICO_LAG", "02_CM_LAG", "07_CASH_LAG"],
  },
  {
    id: "14_DONNA_LAG",
    name: "Executive Assistant Agent",
    shortName: "14_DONNA",
    role: "Asistente Ejecutiva Personal",
    status: "EN DESARROLLO",
    color: "#a855f7",
    icon: UserCheck,
    description: "Supervisión de calidad de contenido, control de calendarios y puente entre CEO y agentes.",
    capabilities: [
      "Supervisión de calidad de contenido",
      "Control de calendarios y deadlines",
      "Puente entre CEO y agentes",
      "Detección de errores y burnout",
      "Velar por ética y valores de La Grieta",
    ],
    integrations: ["00_CEO_LAG", "Todos los agentes", "Google Calendar", "Trello", "Obsidian"],
  },
]

export const systemMetrics = {
  totalAgents: 15,
  operationalAgents: 6,
  developmentAgents: 9,
  totalTasks: 1247,
  completedTasks: 1089,
  systemUptime: "99.7%",
  lastUpdate: new Date().toISOString(),
}

export const workflowData = [
  {
    id: "video-production",
    name: "Producción de Video Completa",
    agents: ["05_MEDIA_LAG", "04_CLIP_LAG", "01_SEO_LAG", "03_PSICO_LAG", "02_CM_LAG", "00_CEO_LAG"],
    status: "active",
    progress: 75,
  },
  {
    id: "community-management",
    name: "Gestión de Comunidad Reactiva",
    agents: ["02_CM_LAG", "03_PSICO_LAG", "00_CEO_LAG"],
    status: "active",
    progress: 90,
  },
  {
    id: "monetization-legal",
    name: "Monetización y Legal",
    agents: ["07_CASH_LAG", "08_LAW_LAG", "00_CEO_LAG", "02_CM_LAG"],
    status: "pending",
    progress: 30,
  },
  {
    id: "web-development",
    name: "Desarrollo de Proyectos",
    agents: ["12_DEV_LAG", "07_CASH_LAG", "08_LAW_LAG", "14_DONNA_LAG", "00_CEO_LAG"],
    status: "active",
    progress: 45,
  },
]

export const projectsData = [
  {
    id: "vhq-system",
    name: "VHQ System Development",
    status: "active",
    progress: 85,
    deadline: "2024-02-15",
    assignedAgents: ["00_CEO_LAG", "09_IT_LAG", "12_DEV_LAG"],
  },
  {
    id: "content-automation",
    name: "Content Production Automation",
    status: "active",
    progress: 70,
    deadline: "2024-02-20",
    assignedAgents: ["04_CLIP_LAG", "05_MEDIA_LAG", "01_SEO_LAG"],
  },
  {
    id: "monetization-setup",
    name: "Monetization Infrastructure",
    status: "pending",
    progress: 25,
    deadline: "2024-03-01",
    assignedAgents: ["07_CASH_LAG", "08_LAW_LAG"],
  },
]
